# ==============================================================================
# development environment config.yml
# ------------------------------------------------------------------------------
#
# Development-specific values. Hugo supports multiple config files with the
# following syntax:
#
# hugo --config=base.toml,child1.toml,child2.toml
#
# If you are using the Quire commands, this will happen automatically.

baseURL: "https://GWU-Museum-Studies.github.io/Museum-Digital-Practice-2022/"
relativeURLs: true
buildDrafts: true
